### ISSUE TITLE
Pictos PUSH et EDIT a changer dans les interfaces

### ISSUE THREAD

**Issue by theblackemperor** [kwemi/Phraseanet#15]
- Overlay de visionnage d'un doc [picto trop grand]
  ![capture d ecran 2015-02-23 a 17 11 24](https://cloud.githubusercontent.com/assets/2347023/6332858/fca0ab14-bb88-11e4-8d4a-6032bf5b91a2.png)
- Fenetre de push [pas le bon picto]
  ![capture d ecran 2015-02-23 a 17 12 03](https://cloud.githubusercontent.com/assets/2347023/6332859/0523f994-bb89-11e4-8693-f5244ddd3734.png)

**Comment by kwemi** [comment]
@theblackemperor Je peux avoir le push en 64px ?

**Comment by theblackemperor** [comment]
tu l'as en 64px deja....
![push](https://cloud.githubusercontent.com/assets/2347023/6551863/54d58db6-c63f-11e4-926d-06b47a1e8113.png)
