### ISSUE TITLE
Test Comportement SearchBar

### ISSUE THREAD

**Issue by theblackemperor** [kwemi/Phraseanet#18]
960px
![capture d ecran 2015-02-23 a 18 31 28](https://cloud.githubusercontent.com/assets/2347023/6333135/f81dea32-bb8a-11e4-8cb1-674baea72686.png)

Large

![capture d ecran 2015-02-23 a 18 32 54](https://cloud.githubusercontent.com/assets/2347023/6333138/fdd19f28-bb8a-11e4-91fd-07cf3d02f69b.png)

**Comment by kwemi** [comment]
A tester.. on se Skype pour ça..
