### ISSUE TITLE
ToDo | Preférénecs d'affichage  / Nbre de resultats 

### ISSUE THREAD

**Issue by theblackemperor** [kwemi/Phraseanet#4]
Laisse pour l'instant de côté le nbre d'éléements selectionnés

![capture d ecran 2015-02-17 a 01 42 02](https://cloud.githubusercontent.com/assets/2347023/6221631/7b2b4dc4-b646-11e4-9a49-9483e1197f97.png)
![capture d ecran 2015-02-17 a 01 41 38](https://cloud.githubusercontent.com/assets/2347023/6221632/7b2fdfba-b646-11e4-918c-4c3673d28975.png)

**Comment by kwemi** [comment]
@theblackemperor j'ai pas de bouton "affichage", y'a un truc à faire pour l'afficher ?

**Comment by theblackemperor** [comment]
Bouton "préférences" qui doit revenir là haut avec Picto

**Comment by theblackemperor** [comment]
Le picto est dans les Glyphicons si disponible dans les sources
