### ISSUE TITLE
COmpteur de documents selectionnés

### ISSUE THREAD

**Issue by guillaumemaubert** [kwemi/Phraseanet#60]
Dès que l'on depasse 9 documents selectionnées 
"selectionnés " passe à la ligne et se superpose sur le "nombre compté"

**Comment by theblackemperor** [comment]
![capture d ecran 2015-04-16 a 10 54 41](https://cloud.githubusercontent.com/assets/2347023/7177455/16b58a80-e427-11e4-85fe-ce4e30b1ca53.png)
On perd "selectionné"
