### ISSUE TITLE
Mauvaise affichage d'un panier recu "push" 

### ISSUE THREAD

**Issue by guillaumemaubert** [kwemi/Phraseanet#61]
IL est encore affiché avec la barre jaune qui illustrait un nouveau panier recu non ouvert.

IL faut prévoir dans la  refonte de marquer graphiquement un nouveau panier recu

**Comment by theblackemperor** [comment]
Il y aune class "unread" dans la balise de ce panier. 

![capture d ecran 2015-04-02 a 18 36 18](https://cloud.githubusercontent.com/assets/2347023/6968465/667fc712-d967-11e4-86c2-381848455826.png)

##Nveau template (helvetica bold oblique + pictogramme qui change)
![capture d ecran 2015-04-02 a 18 39 35](https://cloud.githubusercontent.com/assets/2347023/6968500/a5478ef8-d967-11e4-83b3-ac756459a5b2.png)

##Picto 
![unread-basket](https://cloud.githubusercontent.com/assets/2347023/6968517/c08038fa-d967-11e4-9048-83f3f477fa63.png)

**Comment by theblackemperor** [comment]
Attention. Le pictogramme ne correspond que a la classe "UNREAD" comme indiqué au dessus

**Comment by theblackemperor** [comment]
Visiblement ca ne passe pas. L'ancien comportement ne capture : 

![capture d ecran 2015-04-07 a 19 32 50](https://cloud.githubusercontent.com/assets/2347023/7029310/16fe25ea-dd5d-11e4-9f14-4dc70f1e45da.png)
