### ISSUE TITLE
Non rafraichissement automatique de la zone des paniers 

### ISSUE THREAD

**Issue by guillaumemaubert** [kwemi/Phraseanet#62]
Quand un utilisateur recoit un panier par push , la zone de travail devrait afficher automatique le panier recu
IL faut en l'etat rafraichir manuellement

**Comment by theblackemperor** [comment]
C'était le cas avant ? Ca rafraichissait automatiquement ?

**Comment by theblackemperor** [comment]
Notification apparait en dessous des onglets.L'id de la balise est "alert_datas_changed"
![capture d ecran 2015-04-02 a 18 30 43](https://cloud.githubusercontent.com/assets/2347023/6968415/f9d48670-d966-11e4-9049-1db90de02d14.png)
![capture d ecran 2015-04-02 a 18 27 40](https://cloud.githubusercontent.com/assets/2347023/6968416/f9d51d9c-d966-11e4-988d-5ff38956d4d4.png)
